# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
# it is writing in this article elasticsearch that how can run: https://www.elastic.co/downloads/elasticsearch
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
#        app: ~
        products_index:
            client: default
            index_name: products_%kernel.environment%
            types:
                products:
                    properties:
                        id: ~
                        name: ~
                        slug: ~
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\Products
                        provider: ~
                        finder: ~
