vich_uploader:
    db_driver: orm
    mappings:
        profile_image:
            uri_prefix: '%upload.profile.images.path%'
            upload_destination: '%kernel.project_dir%/public%upload.profile.images.path%'
        category_image:
            uri_prefix: '%upload.category.images.path%'
            upload_destination: '%kernel.project_dir%/public%upload.category.images.path%'
        product_images:
            uri_prefix: '%upload.product.images.path%'
            upload_destination: '%kernel.project_dir%/public%upload.product.images.path%'