# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
  entities:
    Products:
      class: App\Entity\Products
      label: 'Products'
      image_base_path: 'http://static.acme.org/img/'
      permissions:
        list:  ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN']
      show:
        max_results: 5
      list:
        fields:
        - id
        - name
        - { property: 'code', help: 'EAN-13 valid code. Leave empty if unknown.' }
        - stock
        - status
        - productImages
        - { property: 'isactive', type: 'toggle' }
        - { property: 'isdelete', type: 'toggle' }
        - brand
        - category
        - shop
        - { property: 'createdAt', type: 'datetime' }
        - { property: 'updatedAt', type: 'datetime' }
        title: "Most recent Categories"
        max_results: 10
#        dql_filter: "entity.shop.user.roles like 'ROLE_SUPER_ADMIN%'"
      form:  # <-- 'form' is applied to both 'new' and 'edit' views
        fields:
        - slug
        - name
        - code
        - stock
        - { property: subDescription, type: 'textarea'}
        - { property: description, type: 'textarea'}
        - metatags
        - metakeys
        - status
        - isActive
        - isDelete
        - brand
        - category
        - shop
        - { property: buyPrice, type: 'money', type_options: { currency: 'TRY' }}
        - { property: sellPrice, type: 'money', type_options: { currency: 'TRY' }}
        - { property: taxPrice, type: 'money', type_options: { currency: 'TRY' }}
        - { property: otherPrice, type: 'money', type_options: { currency: 'TRY' }}
        - { property: 'createdAt', type: 'datetime', type_options: { widget: 'single_text' }  }
        - { property: 'updatedAt', type: 'datetime', type_options: { widget: 'single_text' }  }
        - property: 'productImages'
          type: 'collection'
          type_options:
            entry_type: 'App\Form\ProductImagesType'
            allow_delete: true
            allow_add: true
            by_reference: false
